# The following options are needed to support headless chrome testing
dist: trusty
addons:
  chrome: stable

language: ruby
rvm: 2.4.2
cache: bundler
# Travis CI clones repositories to a depth of 50 commits, which is only really
# useful if you are performing git operations.
# https://docs.travis-ci.com/user/customizing-the-build/#Git-Clone-Depth
git:
  depth: 3

before_install:
  - export TZ=UTC
  - gem install -v 1.17.2 bundler --no-rdoc --no-ri

before_script:
  - bundle exec rake run

script:
  - bundle exec quke
