name: CI

on: push

jobs:
  build:
    # You must use a Linux environment when using service containers or container jobs
    runs-on: ubuntu-latest

    steps:
      # Downloads a copy of the code in your repository before running CI tests
      - name: Checkout repository
        uses: actions/checkout@v2

      # We don't have to specify the ruby version, or grab it from .ruby-verion. This action supports reading the
      # version from .ruby-verion itself
      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      # Start our test app which we use to run our example scenarios against
      - name: Start example app
        run: |
          nohup bundle exec rake run > nohup.out 2>&1 &

      - name: Run scenarios
        run: |
          bundle exec quke
